data = [
    {'name': 'Instagram', 'follower_count': 691, 'description': 'Social media platform', 'country': 'Global'},
    {'name': 'Cristiano Ronaldo', 'follower_count': 659, 'description': 'Footballer', 'country': 'Portugal'},
    {'name': 'Lionel Messi', 'follower_count': 505, 'description': 'Footballer', 'country': 'Argentina'},
    {'name': 'Selena Gomez', 'follower_count': 419, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Kylie Jenner', 'follower_count': 393, 'description': 'Media personality', 'country': 'United States'},
    {'name': 'Dwayne Johnson', 'follower_count': 393, 'description': 'Actor and wrestler', 'country': 'United States'},
    {'name': 'Ariana Grande', 'follower_count': 375, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Kim Kardashian', 'follower_count': 356, 'description': 'Media personality', 'country': 'United States'},
    {'name': 'Beyoncé', 'follower_count': 311, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Khloé Kardashian', 'follower_count': 302, 'description': 'Media personality', 'country': 'United States'},
    {'name': 'Nike', 'follower_count': 301, 'description': 'Sportswear brand', 'country': 'United States'},
    {'name': 'Justin Bieber', 'follower_count': 294, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Kendall Jenner', 'follower_count': 287, 'description': 'Media personality', 'country': 'United States'},
    {'name': 'Taylor Swift', 'follower_count': 281, 'description': 'Musician', 'country': 'United States'},
    {'name': 'National Geographic', 'follower_count': 278, 'description': 'Magazine', 'country': 'United States'},
    {'name': 'Virat Kohli', 'follower_count': 273, 'description': 'Cricketer', 'country': 'India'},
    {'name': 'Jennifer Lopez', 'follower_count': 248, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Neymar', 'follower_count': 230, 'description': 'Footballer', 'country': 'Brazil'},
    {'name': 'Nicki Minaj', 'follower_count': 225, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Kourtney Kardashian', 'follower_count': 218, 'description': 'Media personality', 'country': 'United States'},
    {'name': 'Miley Cyrus', 'follower_count': 212, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Katy Perry', 'follower_count': 204, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Zendaya', 'follower_count': 178, 'description': 'Actress and singer', 'country': 'United States'},
    {'name': 'Kevin Hart', 'follower_count': 177, 'description': 'Comedian and actor', 'country': 'United States'},
    {'name': 'Real Madrid CF', 'follower_count': 176, 'description': 'Football club', 'country': 'Spain'},
    {'name': 'Cardi B', 'follower_count': 163, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'LeBron James', 'follower_count': 159, 'description': 'Basketball player', 'country': 'United States'},
    {'name': 'Demi Lovato', 'follower_count': 153, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Rihanna', 'follower_count': 149, 'description': 'Musician and businesswoman', 'country': 'Barbados'},
    {'name': 'Chris Brown', 'follower_count': 144, 'description': 'Musician', 'country': 'United States'}
]
